const state = { token: localStorage.getItem('blog_token'), user: JSON.parse(localStorage.getItem('blog_user') || 'null') };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function initials(name) { return (name || '?').trim().charAt(0).toUpperCase(); }
function note(element, message, good = false) { element.textContent = message; element.style.color = good ? 'var(--green)' : 'var(--coral)'; }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); }
async function api(path, options = {}) { const headers = {'Content-Type':'application/json', ...(options.headers || {})}; if (state.token) headers.Authorization = `Bearer ${state.token}`; const response = await fetch(path, {...options, headers}); const data = response.status === 204 ? null : await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error || 'Request failed'); return {data, response}; }
function setSession() { const signedIn = Boolean(state.token && state.user); $('#auth-panel').classList.toggle('hidden', signedIn); $('#app-panel').classList.toggle('hidden', !signedIn); $('#logout').classList.toggle('hidden', !signedIn); $('#session-label').textContent = signedIn ? state.user.email : 'Not signed in'; if (signedIn) { $('#profile-name').textContent = state.user.display_name; $('#profile-email').textContent = state.user.email; ['avatar','composer-avatar'].forEach(id => { $(('#' + id)).textContent = initials(state.user.display_name); }); $('#api-status').textContent = 'API connected'; loadFeed(); } }
function saveSession(token, user) { state.token = token; state.user = user; localStorage.setItem('blog_token', token); localStorage.setItem('blog_user', JSON.stringify(user)); setSession(); }
function formatDate(value) { return new Intl.DateTimeFormat(undefined, {month:'short', day:'numeric', year:'numeric'}).format(new Date(value)); }
function commentTree(comments, postId, depth = 0) { return comments.map(comment => `<div class="comment ${depth ? 'reply' : ''}"><small><strong>${esc(comment.author_name)}</strong> · ${formatDate(comment.created_at)}</small><p>${esc(comment.body)}</p>${comment.replies?.length ? commentTree(comment.replies, postId, depth + 1) : ''}</div>`).join(''); }
async function renderComments(postId, container) { try { const {data} = await api(`/api/v1/posts/${postId}/comments`); container.innerHTML = `<div class="comment-list">${data.comments.length ? commentTree(data.comments, postId) : '<small>No comments yet.</small>'}</div><form class="comment-form"><input name="body" placeholder="Add to the thread..." required><button title="Add comment">→</button></form>`; container.querySelector('form').addEventListener('submit', async (event) => { event.preventDefault(); const body = new FormData(event.currentTarget).get('body'); try { await api(`/api/v1/posts/${postId}/comments`, {method:'POST', body:JSON.stringify({body})}); await renderComments(postId, container); } catch (error) { toast(error.message); } }); } catch (error) { toast(error.message); } }
async function loadFeed() { const feed = $('#feed'); feed.innerHTML = '<div class="empty">Loading the latest notes...</div>'; try { const {data, response} = await api('/api/v1/feed?page=1'); $('#cache-state').textContent = response.headers.get('X-Cache') === 'HIT' ? 'REDIS / CACHED' : 'POSTGRES / FRESH'; $('#empty-feed').classList.toggle('hidden', data.posts.length > 0); feed.innerHTML = data.posts.map((post, index) => `<article class="post panel" style="animation-delay:${index * 45}ms" data-id="${post.id}"><div class="post-meta"><div class="author"><div class="avatar small">${initials(post.author_name)}</div><span class="author-name">${esc(post.author_name)}</span></div><span class="post-date">${formatDate(post.created_at)}</span></div><h3>${esc(post.title)}</h3><p class="post-body">${esc(post.body)}</p><div class="post-actions"><button class="comment-toggle">View thread</button><div><button class="edit-post">Edit</button><button class="delete-post">Delete</button></div></div><div class="comments hidden"></div></article>`).join(''); feed.querySelectorAll('.comment-toggle').forEach(button => button.addEventListener('click', async () => { const post = button.closest('.post'); const comments = post.querySelector('.comments'); comments.classList.toggle('hidden'); button.textContent = comments.classList.contains('hidden') ? 'View thread' : 'Hide thread'; if (!comments.classList.contains('hidden')) await renderComments(post.dataset.id, comments); })); feed.querySelectorAll('.delete-post').forEach(button => button.addEventListener('click', async () => { if (!confirm('Delete this post?')) return; try { await api(`/api/v1/posts/${button.closest('.post').dataset.id}`, {method:'DELETE'}); toast('Post deleted'); loadFeed(); } catch (error) { toast(error.message); } })); feed.querySelectorAll('.edit-post').forEach(button => button.addEventListener('click', async () => { const post = button.closest('.post'); const title = prompt('Title', post.querySelector('h3').textContent); if (title === null) return; const body = prompt('Body', post.querySelector('.post-body').textContent); if (body === null) return; try { await api(`/api/v1/posts/${post.dataset.id}`, {method:'PUT', body:JSON.stringify({title, body})}); toast('Post updated'); loadFeed(); } catch (error) { toast(error.message); } })); } catch (error) { feed.innerHTML = ''; toast(error.message); } }
$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const {data} = await api('/api/v1/auth/login', {method:'POST', body:JSON.stringify(Object.fromEntries(form))}); saveSession(data.token, data.user); } catch (error) { note($('#login-message'), error.message); } });
$('#register-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const {data} = await api('/api/v1/auth/register', {method:'POST', body:JSON.stringify({email:form.get('email'), password:form.get('password'), displayName:form.get('displayName')})}); if (data.verification_token) { $('#verify-form input[name="token"]').value = data.verification_token; note($('#register-message'), 'Created. The development token was placed in Verify email.', true); } else { note($('#register-message'), 'Created. Check your email to verify.', true); } toast('Account created'); } catch (error) { note($('#register-message'), error.message); } });
$('#verify-form').addEventListener('submit', async (event) => { event.preventDefault(); const token = new FormData(event.currentTarget).get('token'); try { await api(`/api/v1/auth/verify?token=${encodeURIComponent(token)}`, {method:'GET'}); note($('#verify-message'), 'Verified. You can sign in now.', true); toast('Email verified'); } catch (error) { note($('#verify-message'), error.message); } });
$('#post-form').addEventListener('submit', async (event) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await api('/api/v1/posts', {method:'POST', body:JSON.stringify({title:form.get('title'), body:form.get('body')})}); formElement.reset(); note($('#post-message'), 'Published.', true); loadFeed(); } catch (error) { note($('#post-message'), error.message); } });
$('#refresh-feed').addEventListener('click', loadFeed); $('#logout').addEventListener('click', () => { state.token = null; state.user = null; localStorage.clear(); setSession(); });
setSession();
